export enum Abilities {
  BUG = 'Bug',
  DARK = 'Dark',
  DRAGON = 'Dragon',
  ELETRIC = 'Eletric',
  FAIRY = 'Fairy',
  FIGHTING = 'Fighting',
  FIRE = 'Fire',
  FLYING = 'Flying',
  GHOST = 'Ghost',
  GRASS = 'Grass',
  GROUND = 'Ground',
  ICE = 'Ice',
  NORMAL = 'Normal',
  POISON = 'Poison',
  PSYCHIC = 'Psychic',
  ROCK = 'Rock',
  STEEL = 'Steel',
  WATER = 'Water'
}
